package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class PksdemoappApplication {

	@RequestMapping("/")
	public String hello() {
		String java_ver = System.getProperty("java.vm.version");
		String app_ver = "3";
		String app_index = System.getenv("MY_POD_UID");
		String app_host = System.getenv("MY_POD_IP");
		return "MMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFMMMMMMMMM\n"+
               "MMMMMMMMMMMMMMMMMMMMMMMM@^  7WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMMMMMMMMMMMl        .THMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMMMMMMMMMM# (((,        .TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMMMMMYMMMM#    ,MN.,        ?TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMM`     7WN.   ,MMMMMN,.       dMMMMMMMMM ..... ?MMF dMMMMMMMMMMMMMMMMMMMMMMTMMMMMMMMMMMM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMu,        .MG,,MMMMMMMMNg,    dMMMMMMMMM MMMMMN,.MMMMMMMMMMMMMMMMMHMHMMMMM!,MMMMMMMHMMMM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMN   (4J,        -TMMMMMMMMM]    dMMMMMMMMM MMMMMM'.M@ MN vMMMM^.M#'.(ga,.MNJ..JJM[.+gg,.MM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MM#=  ?YMMN    .MMMN.,        (WMMMMM]    dMMMMMMMMM .......MM@ MMb WMMD.MM!.MMMMM;.MM!,MMMM9MMME dM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "5         76,. .MMMMM#?4..     (MMMMM]    dMMMMMMMMM MMMMMMMMM@ MMMp MF dMM.-MMMMM%.MM!,MM# .MMMp dM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               " .Ma,        .MwMMMMM#   .F    (MMMMM]  ` dMMMMMMMMM MMMMMMMMM@ MMMM,. -MMMh.?HM#= JMM;,MMN ?MMMD dM# dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "     MNJ,        .TMM#    F    (MMMMM]    dMMMMMMMMMggMMMMMMMMNgMMMMMggMMMMMMN+-(gMMMMN&-+MMg(-gNgMMNgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "     MMMMMN(.       -MNa, F    (  7WM]    dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "     MMMMMN  74,    ,MMMMMF  ` (     ]    dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "     MMMMMN    P    ,MMMMMF    (,    ]   .dMMMMMMMMMM@^      7MMMMMMMMMMMMMMMMMMMMMMM#MMHMMMMMMMMMMMM.  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#^      ?WMMMMMMMMMMMMMMMMMMMMMMMMMM#  ,MMMMMMMMMMMMMMMMMMMMMMM\n"+
               "     MMMMMM,.  P   `,YYMMMF    (MMN,.]..MMMMMMMMMMMM'  .MMMm,..MMMMMMMMMMMMMMMMMMWMMME  dMMMMHMMWMMMM#UMMMMMMMMMWMMMMMMMMWMMMMMMMM#WMMMM#  .MMMN,.MMMMMMMWMMMMMMMM#WMMMMMMMMMMBTMMMMMYMMMMMMMMYMMMMMMMMM\n"+
               "     MMMMMMMMNaP    ,{   TF    (MMMMMMMMMMMMMMMMMMM%  dMMMMMMMMM@` ...  TM#   ...  M[.  ..Mb .... ,MM) ,M@   ..   MMF  .., .MM]   ..MMMMM,   ?MMHMMMF  .., .MM[   ... -MMM' .M  (M#!  .. .M#! ..,  TNd(J\n"+
               "     TMMMMMMMMM@    ,{    F    (MMMMMMMMMMMMMMMMMMM|  MMMMMMMMM#  .MMMb  d#  dMM#  dM#  dMMMMMMTB  dM) ,M@  MMM#  d#  ?MMM% .M] .MMMMMMMMMN-..    4#  ?MMM3 .M[ .MMMN  4M$ .MM  (M` .MMMMMM` ,MMM5  MMMM\n"+
               "        ?MMMMMM@   `,NJ,  F  .JMMMMMMMMMMMMMMMMMMMMb  ,HMMMMDMWN  ?MMMF  J#  dMM#  dM#  dM#  .gN,  dM) ,M@  MMM#  dN  (++++++M] .MMMMMMMM@TMMMMN  .@  (++++++M[ .MMMMb  D  dMM  (M. -MMMMMM. .++++++MMMM\n"+
               "Ma,.        ?WM@    ,MMMMNmgMMMMMMMMMMMMMMMMMMMMMMMMN,       .(Mb.  ?!  .M#  dMM#  dMN  .!N, ,MM^  dM) ,M@  MMM#  dML  (MM!,MM] .MMMMMMMh.   ``  .JMp  (MM!,MM[ .MMMMMp   -MMM  (Mh.  ?! .MN, .7^ WMMMMM\n"+
               "MMMMNa,        P    ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNg++gMMMMMMNg++gMMMNggMMMNggMMMNg+&MMNg+gNggMMNggMNggMMMNggMMMMNg++gMMMNggMMMMMMMMMMNg++gMMMMMMNg++gMMMNggMMMMMMgggMMMMggdMMMNg++gMMMMNg++gMMMMMM\n"+
               "MMMMMMMMN&,    P    -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMNJ.P..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"+
               "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+"\r\n"
				+"Current app version = " + app_ver
				+"\r\n"
				+"Current java version = " + java_ver
				+"\r\n"
				+"Pod UID = " + app_index
				+"\r\n"
				+"Pod host = " + app_host;
	}
	
	
	public static void main(String[] args) {
		SpringApplication.run(PksdemoappApplication.class, args);
	}
}
